import { Product, Category, Order, Review } from '@/types';

// ===== MOCK PRODUCTS =====
export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Sony WH-1000XM5 Wireless Headphones',
    slug: 'sony-wh-1000xm5',
    description: 'Industry-leading noise canceling with two processors and eight microphones. 30-hour battery life with quick charging. Multipoint connection for two devices simultaneously.',
    price: 279.99,
    originalPrice: 399.99,
    discount: 30,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&q=80',
    ],
    category: 'Electronics',
    subcategory: 'Headphones',
    brand: 'Sony',
    rating: 4.8,
    reviewCount: 2847,
    stock: 48,
    sku: 'SNY-WH1000XM5-BLK',
    tags: ['wireless', 'noise-canceling', 'premium', 'audio'],
    isFeatured: true,
    isBestSeller: true,
    specifications: {
      'Driver Unit': '30mm, dome type',
      'Frequency Response': '4Hz – 40,000Hz',
      'Battery Life': '30 hours (NC ON)',
      'Charging Time': '3.5 hours',
      'Weight': '250g',
      'Connectivity': 'Bluetooth 5.2, 3.5mm jack',
    },
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: '2',
    name: 'MacBook Pro 16" M3 Pro Chip',
    slug: 'macbook-pro-16-m3',
    description: 'Supercharged by M3 Pro, MacBook Pro takes performance to the next level. With an immersive Liquid Retina XDR display and all-day battery life.',
    price: 1999.99,
    originalPrice: 2499.99,
    discount: 20,
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80',
      'https://images.unsplash.com/photo-1611186871525-b5a4fc3ec5a6?w=800&q=80',
    ],
    category: 'Electronics',
    subcategory: 'Laptops',
    brand: 'Apple',
    rating: 4.9,
    reviewCount: 1283,
    stock: 12,
    sku: 'AAPL-MBP16-M3PRO',
    tags: ['laptop', 'apple', 'pro', 'M3'],
    isFeatured: true,
    isNew: true,
    specifications: {
      'Chip': 'Apple M3 Pro',
      'Memory': '36GB unified memory',
      'Storage': '512GB SSD',
      'Display': '16.2" Liquid Retina XDR',
      'Battery': 'Up to 22 hours',
      'Weight': '2.14 kg',
    },
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: '3',
    name: 'Nike Air Jordan 1 Retro High OG',
    slug: 'nike-air-jordan-1-retro',
    description: 'The shoes that started it all. The Air Jordan 1 Retro High OG features premium leather in the upper with foam midsole for lightweight cushioning.',
    price: 180.00,
    originalPrice: 180.00,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
      'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800&q=80',
    ],
    category: 'Fashion',
    subcategory: 'Sneakers',
    brand: 'Nike',
    rating: 4.7,
    reviewCount: 4521,
    stock: 34,
    sku: 'NK-AJ1-RETRO-HI',
    tags: ['sneakers', 'basketball', 'retro', 'iconic'],
    isFeatured: true,
    isBestSeller: true,
    specifications: {
      'Upper': 'Full-grain leather',
      'Midsole': 'Foam',
      'Outsole': 'Rubber',
      'Closure': 'Lace-up',
      'Country': 'China',
    },
    createdAt: '2024-01-20T00:00:00Z',
  },
  {
    id: '4',
    name: 'Samsung Galaxy S24 Ultra',
    slug: 'samsung-galaxy-s24-ultra',
    description: 'The most powerful Galaxy ever with built-in S Pen. 200MP camera with AI-powered features and 12GB RAM for seamless performance.',
    price: 1299.99,
    originalPrice: 1399.99,
    discount: 7,
    images: [
      'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800&q=80',
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=80',
    ],
    category: 'Electronics',
    subcategory: 'Smartphones',
    brand: 'Samsung',
    rating: 4.6,
    reviewCount: 3102,
    stock: 67,
    sku: 'SAM-S24-ULTRA-256',
    tags: ['smartphone', 'android', 'flagship', 'camera'],
    isFeatured: true,
    isNew: true,
    specifications: {
      'Display': '6.8" QHD+ Dynamic AMOLED 2X',
      'Processor': 'Snapdragon 8 Gen 3',
      'RAM': '12GB',
      'Storage': '256GB',
      'Camera': '200MP + 12MP + 10MP + 50MP',
      'Battery': '5000mAh',
    },
    createdAt: '2024-02-10T00:00:00Z',
  },
  {
    id: '5',
    name: 'Dyson V15 Detect Cordless Vacuum',
    slug: 'dyson-v15-detect',
    description: 'Dyson\'s most powerful cordless vacuum with laser to reveal hidden dust. Intelligently adapts suction to the task and counts and sizes microscopic particles.',
    price: 549.99,
    originalPrice: 699.99,
    discount: 21,
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    ],
    category: 'Home & Living',
    subcategory: 'Appliances',
    brand: 'Dyson',
    rating: 4.5,
    reviewCount: 892,
    stock: 23,
    sku: 'DYS-V15-DETECT',
    tags: ['vacuum', 'cordless', 'home', 'cleaning'],
    specifications: {
      'Motor': 'Dyson Hyperdymium',
      'Suction': 'Up to 230 AW',
      'Run time': 'Up to 60 min',
      'Weight': '3.1 kg',
      'Filtration': 'Whole-machine HEPA',
    },
    createdAt: '2024-01-05T00:00:00Z',
  },
  {
    id: '6',
    name: 'Levi\'s 501 Original Fit Jeans',
    slug: 'levis-501-original-jeans',
    description: 'The original jeans. The authentic, rebellious, democratic 501 Original Fit. Made from 100% cotton denim. Button fly closure with straight leg cut.',
    price: 69.50,
    originalPrice: 89.50,
    discount: 22,
    images: [
      'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&q=80',
    ],
    category: 'Fashion',
    subcategory: 'Jeans',
    brand: "Levi's",
    rating: 4.4,
    reviewCount: 6741,
    stock: 120,
    sku: 'LVS-501-ORIG-32-32',
    tags: ['jeans', 'denim', 'classic', 'casual'],
    isBestSeller: true,
    specifications: {
      'Material': '100% Cotton',
      'Fit': 'Original Fit',
      'Rise': 'Regular',
      'Closure': 'Button fly',
      'Care': 'Machine wash cold',
    },
    createdAt: '2024-01-08T00:00:00Z',
  },
  {
    id: '7',
    name: 'Instant Pot Pro 10-in-1 Pressure Cooker',
    slug: 'instant-pot-pro-10in1',
    description: 'Your all-in-one multicooker for pressure cooking, slow cooking, rice cooking, steaming, sautéing, yogurt making, and more. Programmable with 28 pre-set programs.',
    price: 99.95,
    originalPrice: 149.95,
    discount: 33,
    images: [
      'https://images.unsplash.com/photo-1585515320310-259814833e62?w=800&q=80',
    ],
    category: 'Home & Living',
    subcategory: 'Kitchen',
    brand: 'Instant Pot',
    rating: 4.6,
    reviewCount: 11234,
    stock: 85,
    sku: 'IP-PRO-10IN1-6QT',
    tags: ['kitchen', 'pressure cooker', 'multi-cooker', 'cooking'],
    isBestSeller: true,
    specifications: {
      'Capacity': '6 Quart',
      'Programs': '28 pre-set programs',
      'Functions': '10-in-1',
      'Power': '1000W',
      'Material': 'Stainless Steel',
    },
    createdAt: '2024-01-12T00:00:00Z',
  },
  {
    id: '8',
    name: 'Kindle Paperwhite Signature Edition',
    slug: 'kindle-paperwhite-signature',
    description: 'Our most-loved Kindle, now with a 6.8" display, adjustable warm light, and 32 GB storage. Waterproof with wireless charging for up to 10 weeks of battery.',
    price: 139.99,
    originalPrice: 189.99,
    discount: 26,
    images: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&q=80',
    ],
    category: 'Electronics',
    subcategory: 'E-readers',
    brand: 'Amazon',
    rating: 4.7,
    reviewCount: 5632,
    stock: 44,
    sku: 'AMZ-KPW-SIG-32GB',
    tags: ['kindle', 'ebook', 'reading', 'waterproof'],
    isNew: true,
    specifications: {
      'Display': '6.8" 300 PPI Paperwhite',
      'Storage': '32 GB',
      'Battery': 'Up to 10 weeks',
      'Waterproof': 'IPX8',
      'Charging': 'Wireless (Qi)',
    },
    createdAt: '2024-02-15T00:00:00Z',
  },
  {
    id: '9',
    name: 'Weber Spirit II E-310 Gas Grill',
    slug: 'weber-spirit-ii-e310',
    description: 'With the Spirit II E-310, you get the legendary Weber quality with the GS4 grilling system, infinity ignition, and porcelain-enameled cast-iron cooking grates.',
    price: 499.00,
    originalPrice: 629.00,
    discount: 21,
    images: [
      'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
    ],
    category: 'Outdoor',
    subcategory: 'Grills',
    brand: 'Weber',
    rating: 4.5,
    reviewCount: 1847,
    stock: 18,
    sku: 'WBR-SPIIRIT2-E310',
    tags: ['grill', 'outdoor', 'bbq', 'cooking'],
    specifications: {
      'Burners': '3 stainless steel burners',
      'Total cooking area': '529 sq in',
      'BTU': '30,000 BTU-per-hour',
      'Fuel': 'Liquid propane',
      'Ignition': 'Infinity ignition',
    },
    createdAt: '2024-01-25T00:00:00Z',
  },
  {
    id: '10',
    name: 'Fitbit Charge 6 Fitness Tracker',
    slug: 'fitbit-charge-6',
    description: 'Track your health 24/7 with built-in GPS, heart rate monitoring, sleep tracking, and Google services integration. 7-day battery with fast charging.',
    price: 159.95,
    originalPrice: 179.95,
    discount: 11,
    images: [
      'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=800&q=80',
    ],
    category: 'Sports & Fitness',
    subcategory: 'Wearables',
    brand: 'Fitbit',
    rating: 4.3,
    reviewCount: 2193,
    stock: 91,
    sku: 'FTB-CHRG6-BLK',
    tags: ['fitness', 'tracker', 'health', 'wearable'],
    isNew: true,
    specifications: {
      'GPS': 'Built-in',
      'Heart Rate': '24/7 monitoring',
      'Battery': '7 days',
      'Water resistance': '50m',
      'Compatibility': 'Android & iOS',
    },
    createdAt: '2024-02-20T00:00:00Z',
  },
  {
    id: '11',
    name: 'IKEA POÄNG Armchair',
    slug: 'ikea-poang-armchair',
    description: 'The POÄNG armchair has a timeless design that is comfortable and durable. Layer-glued bent birch frame for resilience with cushioned seat and back.',
    price: 149.00,
    images: [
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800&q=80',
    ],
    category: 'Home & Living',
    subcategory: 'Furniture',
    brand: 'IKEA',
    rating: 4.2,
    reviewCount: 8934,
    stock: 67,
    sku: 'IKEA-POANG-BIRCH',
    tags: ['chair', 'furniture', 'living room', 'comfort'],
    isBestSeller: true,
    specifications: {
      'Material': 'Birch veneer, cotton blend',
      'Width': '68 cm',
      'Depth': '82 cm',
      'Height': '100 cm',
      'Max load': '110 kg',
    },
    createdAt: '2024-01-03T00:00:00Z',
  },
  {
    id: '12',
    name: 'GoPro HERO12 Black Action Camera',
    slug: 'gopro-hero12-black',
    description: 'Capture your adventures in stunning 5.3K video. HyperSmooth 6.0 stabilization, 27MP photos, and up to 70 minutes of battery life in a rugged, waterproof body.',
    price: 349.99,
    originalPrice: 399.99,
    discount: 13,
    images: [
      'https://images.unsplash.com/photo-1525459819821-d4654d3d8f32?w=800&q=80',
    ],
    category: 'Electronics',
    subcategory: 'Cameras',
    brand: 'GoPro',
    rating: 4.6,
    reviewCount: 1567,
    stock: 29,
    sku: 'GPR-HERO12-BLK',
    tags: ['camera', 'action', 'waterproof', 'adventure'],
    isNew: true,
    specifications: {
      'Video': '5.3K60 + 4K120',
      'Photo': '27MP',
      'Stabilization': 'HyperSmooth 6.0',
      'Waterproof': '10m',
      'Battery': 'Up to 70 min at 5.3K',
    },
    createdAt: '2024-02-08T00:00:00Z',
  },
];

// ===== MOCK CATEGORIES =====
export const MOCK_CATEGORIES: Category[] = [
  { id: '1', name: 'Electronics', slug: 'electronics', icon: '💻', productCount: 5, gradient: 'linear-gradient(135deg, #7c3aed, #4f46e5)' },
  { id: '2', name: 'Fashion', slug: 'fashion', icon: '👗', productCount: 2, gradient: 'linear-gradient(135deg, #ec4899, #8b5cf6)' },
  { id: '3', name: 'Home & Living', slug: 'home-living', icon: '🏡', productCount: 3, gradient: 'linear-gradient(135deg, #06b6d4, #0891b2)' },
  { id: '4', name: 'Sports & Fitness', slug: 'sports-fitness', icon: '🏃', productCount: 1, gradient: 'linear-gradient(135deg, #10b981, #059669)' },
  { id: '5', name: 'Outdoor', slug: 'outdoor', icon: '🌲', productCount: 1, gradient: 'linear-gradient(135deg, #f59e0b, #d97706)' },
  { id: '6', name: 'Beauty', slug: 'beauty', icon: '✨', productCount: 0, gradient: 'linear-gradient(135deg, #f472b6, #ec4899)' },
];

// ===== MOCK REVIEWS =====
export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1', userId: 'u2', userName: 'Sarah Mitchell', productId: '1',
    rating: 5, title: 'Absolutely incredible noise cancellation!',
    body: 'These headphones have completely transformed my work-from-home experience. The noise cancellation is so effective that I can focus even when my kids are being loud. The sound quality is crisp, warm, and detailed. Battery life is excellent. Worth every penny.',
    helpful: 47, createdAt: '2024-03-15T00:00:00Z',
  },
  {
    id: 'r2', userId: 'u3', userName: 'James Chen', productId: '1',
    rating: 4, title: 'Great headphones, minor fit issues',
    body: 'Sound quality is exceptional and the NC is top tier. My only gripe is they get slightly uncomfortable after 3-4 hours. But overall an excellent product that I would recommend to anyone looking for premium headphones.',
    helpful: 23, createdAt: '2024-03-10T00:00:00Z',
  },
  {
    id: 'r3', userId: 'u4', userName: 'Priya Sharma', productId: '2',
    rating: 5, title: 'The best laptop I have ever owned',
    body: 'The M3 Pro chip is a beast. I run multiple virtual machines, 4K video editing, and Xcode simultaneously with zero lag. The display is stunning. Battery lasts all day easily. If you are a pro who needs serious power, this is it.',
    helpful: 89, createdAt: '2024-03-20T00:00:00Z',
  },
];

// ===== MOCK ORDERS =====
export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-2024-001',
    userId: 'u1',
    items: [
      { product: MOCK_PRODUCTS[0], quantity: 1 },
      { product: MOCK_PRODUCTS[7], quantity: 1 },
    ],
    total: 419.98,
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    paymentMethod: 'Visa ending in 4242',
    shippingAddress: { street: '123 Tech Street', city: 'Dhaka', state: 'Dhaka', zip: '1212', country: 'Bangladesh' },
    createdAt: '2024-03-01T00:00:00Z',
    updatedAt: '2024-03-05T00:00:00Z',
    trackingNumber: 'TRK-789456123',
  },
  {
    id: 'ORD-2024-002',
    userId: 'u1',
    items: [
      { product: MOCK_PRODUCTS[3], quantity: 1 },
    ],
    total: 1299.99,
    status: 'SHIPPED',
    paymentStatus: 'PAID',
    paymentMethod: 'Mastercard ending in 5678',
    shippingAddress: { street: '456 Digital Ave', city: 'Dhaka', state: 'Dhaka', zip: '1213', country: 'Bangladesh' },
    createdAt: '2024-03-18T00:00:00Z',
    updatedAt: '2024-03-20T00:00:00Z',
    trackingNumber: 'TRK-456789012',
  },
  {
    id: 'ORD-2024-003',
    userId: 'u1',
    items: [
      { product: MOCK_PRODUCTS[2], quantity: 2 },
      { product: MOCK_PRODUCTS[5], quantity: 1 },
    ],
    total: 429.50,
    status: 'PROCESSING',
    paymentStatus: 'PAID',
    paymentMethod: 'Stripe',
    shippingAddress: { street: '789 Commerce Blvd', city: 'Chittagong', state: 'Chittagong', zip: '4100', country: 'Bangladesh' },
    createdAt: '2024-03-22T00:00:00Z',
    updatedAt: '2024-03-22T00:00:00Z',
  },
];
